// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiverBooks.Books;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20240808224656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb57263c-2775-4eb4-b665-6c65f7dcf8b1"),
                            Author = "Eric Evans",
                            Price = 55.90m,
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = new Guid("9334c5ea-92cf-4edf-b263-8e954fba47bf"),
                            Author = "Robert C. Martin",
                            Price = 45.50m,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("a5d6c8c4-6647-4161-9cc3-5c1037e14bad"),
                            Author = "Martin Fowler",
                            Price = 40.00m,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = new Guid("2b1068c3-0a1a-4ce8-8bbf-cce3ee9dac76"),
                            Author = "Erich Gamma",
                            Price = 48.90m,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("b9bf5ec9-9559-45e2-a7ba-0dac14bbba06"),
                            Author = "Michael Feathers",
                            Price = 32.00m,
                            Title = "Working Effectively with Legacy Code"
                        },
                        new
                        {
                            Id = new Guid("bfdef945-0bc2-4686-8c99-2bf6f29aab18"),
                            Author = "Andrew Hunt",
                            Price = 42.00m,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = new Guid("795a6bbe-b3a4-479e-95c9-288e1c31911f"),
                            Author = "Steve McConnell",
                            Price = 38.00m,
                            Title = "Code Complete"
                        },
                        new
                        {
                            Id = new Guid("84e62466-5bcc-4203-8df1-f07238f4aff7"),
                            Author = "Martin Fowler",
                            Price = 50.00m,
                            Title = "Patterns of Enterprise Application Architecture"
                        },
                        new
                        {
                            Id = new Guid("d8bfaa84-a12e-43ea-a2fa-b9a09bef5f30"),
                            Author = "Kent Beck",
                            Price = 45.00m,
                            Title = "Test Driven Development: By Example"
                        },
                        new
                        {
                            Id = new Guid("e5204137-616a-43f7-93d8-3a9ab0cae56d"),
                            Author = "Robert C. Martin",
                            Price = 55.00m,
                            Title = "Clean Architecture"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
